README.old.md
src/Components/App.js
src/Components/Button.js

Add Header and button component

Headerandbutton

---

src/Components/App.js
src/Components/Icon.js
src/Components/Navigation.js
src/Components/Pages.js
src/Components/Step1.js
src/Components/Step2.js
src/Components/Title.js

I have incorporated in the new architecture, the former footer as Navigation component

Incorporate navigation component to diferent steps components

---

src/Components/App.js
src/Components/Pages.js

I've rebuild the state object and stuff related to it .

Rebuilding state object

---

src/Components/Step1.js
src/Components/Step5.js
src/Components/TypeEmailInput.js
src/Components/TypePhoneInput.js

I've created both components for inputs type e-mail and tel. I still have to put the default email input the requires and optionals. Also, I've added a pattern to the tel input

Input type whatever

---

public/locales/data.json
public/locales/es.json
public/messages/src/Components/App.json
public/messages/src/Components/Step1.json
public/messages/src/Components/Step5.json
src/Components/App.js
src/Components/Header.js
src/Components/Step1.js
src/Components/Step3.js
src/Components/Step4.js
src/Components/Step5.js
src/Components/TypeEmailInput.js

Girls, take a look to my code.

Step5 i18n

---

public/locales/data.json
src/Components/Step5.js
src/Components/TypeSelect.js

Add Select component
Delete Type of document
Delete "Parentesco"

Select component

---

src/Components/Navigation.js
src/Components/Step1.js
src/Components/Step2.js
src/scss/Navigation.css

Valid Jump Step link, only in steps 3 4 and 5. 
Hidden in steps 1 and 2.

add Jump step

---

src/Components/App.js
src/Components/Navigation.js
src/Components/Pages.js
src/Components/Steps/Step1.js
src/Components/Steps/Step2.js
src/Components/Steps/Step3.js
src/Components/Steps/Step4.js
src/Components/Steps/Step5.js

GIrls, Alex and I have improved the logic of the routes. Take a look at it!

fix route logic

---

src/Components/App.js
src/Components/Pages.js
src/Components/Steps/Step1.js
src/Components/Steps/Step2.js
src/Components/Sub-components/Calendar.js

Girls, take a look to the inputs of step1 and step2. With this code the data from the inputs is supposed to be saved in the state of app and it seems to work well!

Functions inputs

---

src/Components/App.js
src/Components/Navigation.js
src/Components/Steps/Step1.js
src/Components/Sub-components/Button.js

Fix old stuff

---

public/messages/src/Components/Steps/Step4.json
src/Components/App.js
src/Components/Steps/Step4.js
src/Components/Sub-components/AccommodationPref.js
src/Components/Sub-components/TransportPref.js

Step 4 radio-buttons created to the plain and train options

Transport preferences

---

public/messages/src/Components/Steps/Step2.json
src/Components/App.js
src/Components/Header.js
src/Components/Navigation.js
src/Components/Steps/Step2.js
src/Components/Steps/Step3.js
src/Components/Steps/Step4.js
src/Components/Steps/Step5.js
src/Components/Sub-components/AccommodationPref.js
src/Components/Sub-components/Calendar.js

Add visa details. Still work in progress

Visa button and more

---

src/Components/Steps/Step4.js
src/Components/Sub-components/AccommodationPref.js
src/Components/Sub-components/TransportPref.js
src/Components/Types/TypeCheckboxInput.js

Transport preferences radio-button working well

Pref transport

---

src/Components/Steps/Step2.js
src/Components/Steps/Step5.js
src/Components/Sub-components/Button.js

Add functionality to visaButton

Visa functionality

---

src/Components/App.js
src/Components/Pages.js
src/Components/Steps/Step1.js
src/Components/Steps/Step5.js
src/Components/Types/TypeEmailInput.js
src/Components/Types/TypePhoneInput.js

Girls,  take a look to controlled Step5 inputs.

Save data step5

---

src/Components/Types/TypeEmailInput.js
src/Components/Types/TypePhoneInput.js

Add logic floating labels Step 1.

finished labels step1

---

src/Components/App.js
src/Components/Pages.js
src/Components/Steps/Step1.js
src/Components/Steps/Step4.js

Finish object al control all inputs in step4

Step4 object finish

---

src/Components/Navigation.js
src/Components/Sub-components/Icon.js
src/scss/components/_buttons.scss
src/scss/index.css
src/scss/pages/_navigation.scss

Responsive nav css

---

src/scss/components/_buttons.scss
src/scss/core/_variables.scss
src/scss/index.css
src/scss/pages/_navigation.scss

It works if we eliminated de fixed widths fromm the other css

Finish nav responsive pending the rest responsive

---

src/Components/Steps/Step2.js
src/Components/Steps/Step5.js
src/Components/Types/TypeTextInput.js
src/scss/components/_buttons.scss
src/scss/components/_label.scss
src/scss/index.css
src/scss/layout/_header.scss
src/scss/pages/_app.scss

Add masked inputs and css.
Fixed label family number.

Css masked inputs and step2

---

src/scss/components/_buttons.scss
src/scss/components/_label.scss
src/scss/components/_titles.scss
src/scss/index.css
src/scss/layout/_header.scss
src/scss/pages/_app.scss

The first step is working well in the mobile version.

Step1 responsive

---

src/Components/App.js
src/Components/Base.js
src/Components/Navigation.js
src/Components/Pages.js
src/Components/Steps/Step1.js
src/Components/Steps/Step2.js
src/Components/Steps/Step3.js
src/Components/Steps/Step5.js
src/Components/Sub-components/Button.js
src/Components/Sub-components/Icon.js
src/Components/Sub-components/TransportPref.js
src/Components/Types/TypeEmailInput.js
src/Components/Types/TypeOnOff.js
src/Components/Types/TypePhoneInput.js
src/Components/Types/TypeSelect.js
src/Components/Types/TypeTextInput.js
src/index.js

Fix bug on get petition

---

src/Components/Steps/Step2.js
src/Components/Steps/Step5.js
src/scss/components/_titles.scss
src/scss/core/_variables.scss
src/scss/index.css
src/scss/layout/_header.scss
src/scss/pages/_app.scss
src/scss/pages/_navigation.scss
src/scss/pages/_step4.scss

Add details like margins, lines, color and size of thypography.

add details of css

---

src/Components/Base.js
src/Components/Pages.js

DONE redirection to STEP1 with switch

Redirection

---

src/Components/App.js
src/Components/Base.js
src/Components/Pages.js
src/Components/Steps/Step1.js
src/Components/Types/TypeTextInput.js

FIX bug on BBDD

---

src/Components/App.js
src/Components/Navigation.js
src/Components/Pages.js
src/Components/Steps/Step1.js
src/Components/Steps/Step2.js
src/Components/Steps/Step5.js

FIX inputs

---

src/Components/Types/TypeOnOff.js
src/scss/components/_switcher.scss
src/scss/index.css
src/scss/pages/_app.scss

Fix switch, add div and remove Fragment.
Add a second div.

fix switch residence width

---

src/Components/App.js
src/Components/Base.js
src/Components/ErrorPage.js
src/Components/Header.js
src/Components/Loading.js
src/Components/Navigation.js
src/Components/Pages.js
src/Components/Steps/Step1.js
src/Components/Steps/Step2.js
src/Components/Steps/Step3.js
src/Components/Steps/Step4.js
src/Components/Steps/Step5.js
src/Components/Sub-components/Button.js
src/Components/Sub-components/Icon.js
src/Components/Sub-components/RadioGroup.js
src/Components/Sub-components/Title.js
src/Components/Types/TypeEmailInput.js
src/Components/Types/TypeOnOff.js
src/Components/Types/TypePhoneInput.js
src/Components/Types/TypeSelect.js
src/Components/Types/TypeTextInput.js

Remove console.log.
Indent code.

clean code
